basic.forever(function on_forever() {
    turtle.forward(4)
    turtle.turnRight()
    turtle.forward(1)
    turtle.turnRight()
    turtle.forward(4)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
})
turtle.setPosition(2, 2)
turtle.turnRight()
turtle.setSpeed(20)
